NODE_ENV: 'development'

SERVER:
  PORT: 4000
  JWT:
    SECRET: 'secret'
    EXPIRES_IN: 86400

DATABASE:
  POSTGRES:
    HOST: 'localhost'
    PORT: 5432
    DATABASE: 'postgres'
    SCHEMA: 'bookstore'
    USERNAME: 'postgres'
    PASSWORD: '123456'
    SSL: false
    SYNCHRONIZE: true

AWS:
  REGION: 'us-east-1'
  ACCESS_KEY_ID:
  SECRET_ACCESS_KEY:
  SERVICES:
    S3:
      BUCKET_NAME:
